name: grecho

services:
  db:
    container_name: grecho-db
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: grecho
      POSTGRES_PASSWORD: grecho
      POSTGRES_DB: grecho
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
